### ISSUE TITLE
How do you import them? 

### ISSUE THREAD

**Issue by Hypnotistchris** [ptrumpis/snap-lens-web-crawler#1]
Struggling to import them
Can you give a quick set of steps to do this?
Thanks

**Comment by Hypnotistchris** [comment]
I have created some custom lenses that I have previously published.

I get the UUID for example 866a34595f7c4210a34e4d5d2db9e66b from https://lens.snapchat.com/866a34595f7c4210a34e4d5d2db9e66b

Run it through main.js

Create a folder in import using "unlockable_id"
Download the lens from "lens_url" and the convert it to a .zip using snap-lens-file-extractor placing it in the folder
Create an entry in the lenses database
Create an entry in the other table with the "signature"

Struggling to get it working. Does this sound right to you?

**Comment by Hypnotistchris** [comment]
I have already brought you a coffee. Will buy you a few more if you can help me get my custom lenses.

**Comment by ptrumpis** [comment]
> I have the v3 server up and running and snap camera. So how do I add new lenses? Just patch the exe and search for the uuid in snap camera?

Exactly,
If your lens was published after January 25 it might not work at all.

**Comment by Hypnotistchris** [comment]
The problem is I need to publish a few more.
I will use a lower version of lens studio. Publish it and try what you said. They steps I have already outlined using your javascript get me all the way to having a zip but as I said not working. Could be the latest version of lens studio or something.

**Comment by ptrumpis** [comment]
Please post your non working lenses here
[List of non working lenses](https://github.com/ptrumpis/snap-camera-server/discussions/8)
